version: '3.0'
services:
  es7:
    container_name: es7
    build: docker/elasticsearch7/
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch7/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    networks:
      - default

  redis:
    image: 'redis:4-alpine'
    networks:
      - default
