version: '3.0'
services:
  app:
    # image: divante/vue-storefront-api:latest
    build:
      context: .
      dockerfile: docker/vue-storefront-api/Dockerfile
    depends_on:
      - es7
      - redis
    env_file: docker/vue-storefront-api/default.env
    environment:
      VS_ENV: dev
    volumes:
      - './config:/var/www/config'
      - './ecosystem.json:/var/www/ecosystem.json'
      - './migrations:/var/www/migrations'
      - './package.json:/var/www/package.json'
      - './babel.config.js:/var/www/babel.config.js'
      - './tsconfig.json:/var/www/tsconfig.json'
      - './nodemon.json:/var/www/nodemon.json'
      - './scripts:/var/www/scripts'
      - './src:/var/www/src'
      - './var:/var/www/var'
      -  'app-media:/var/www/media'
    tmpfs:
      - /var/www/dist
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.veloshops-vsa-app-nginx.entrypoints=http"
      - "traefik.http.routers.veloshops-vsa-app-nginx.rule=Host(`${APP_HOST}`)"
      - "traefik.http.middlewares.veloshops-vsa-app-nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.veloshops-vsa-app-nginx.middlewares=veloshops-vsa-app-nginx-https-redirect"
      - "traefik.http.routers.veloshops-vsa-app-nginx-secure.entrypoints=https"
      - "traefik.http.routers.veloshops-vsa-app-nginx-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.veloshops-vsa-app-nginx-secure.tls=true"
      - "traefik.http.routers.veloshops-vsa-app-nginx-secure.tls.certresolver=http"
      - "traefik.http.routers.veloshops-vsa-app-nginx-secure.service=veloshops-vsa-app-nginx"
      - "traefik.http.services.veloshops-vsa-app-nginx.loadbalancer.server.port=8080"
    networks:
      - default
      - traefik

volumes:
  app-media:
    external: true
